name: Build, test and deploy project

on:
  push: # trigger on git push
  workflow_dispatch: # allow manual trigger

jobs:
  build-and-test-and-deploy-project:
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create pypi config file
        run: echo -e '[pypi]\nusername = __token__\npassword = "${{ secrets.PIP_PASSWORD }}"' > .pypirc

      - name: Install prerequisites
        run: sudo apt-get install --yes twine

      - name: Upgrade pip
        run: sudo pip install --upgrade pip

      - name: Upgrade cryptography
        run: sudo pip install --upgrade cryptography

      - name: Set up ruby
        uses: ruby/setup-ruby@v1.61.1
        with:
          ruby-version: 2.7

      - name: Install tau
        run: gem install takelage

      - name: Configure tau
        run: |
          echo "docker_entrypoint_options: --no-git --no-gopass --no-gpg --no-ssh" >> $HOME/.takelage.yml
          cat $HOME/.takelage.yml

      - name: Pull takelage image
        run: tau update

      - name: Start an instance of takelage
        run: tau docker container daemon

      - name: Move pypi config file
        run: tau docker container command "mv /project/.pypirc $HOME"

      - name: Lint ruby
        run: tau docker container command "rake rubylint"

#      - name: Run tests
#        run: tau docker container command "rake test"

      - name: Build pip package
        run: tau docker container command "rake package:make"

      - name: Upload pip package
        run: tau docker container command "rake package:upload"
